// <auto-generated />
using System;
using BuddyTech.API.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuddyTech.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205053049_AjusteFinalRelacionamentos")]
    partial class AjusteFinalRelacionamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuddyTech.API.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RevenueRange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BuddyTech.API.Models.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CloseDate")
                        .HasColumnType("date");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<Guid?>("CurrentScoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpectedCloseDate")
                        .HasColumnType("date");

                    b.Property<string>("LeadSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<double>("ProbabilityOfClosing")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CurrentScoreId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("BuddyTech.API.Models.LeadInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InteractionContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("InteractionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<int>("TypeOfContact")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadInteractions");
                });

            modelBuilder.Entity("BuddyTech.API.Models.LeadScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadScores");
                });

            modelBuilder.Entity("BuddyTech.API.Models.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Description")
                        .HasColumnType("integer");

                    b.Property<int>("PointsGiven")
                        .HasColumnType("integer");

                    b.Property<int>("Title")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("BuddyTech.API.Models.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("BuddyTech.API.Models.SellerMission", b =>
                {
                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("SellerId", "MissionId");

                    b.HasIndex("MissionId");

                    b.ToTable("SellerMissions");
                });

            modelBuilder.Entity("BuddyTech.API.Models.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InteractionSuggestedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InteractionSuggestedId");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("BuddyTech.API.Models.Lead", b =>
                {
                    b.HasOne("BuddyTech.API.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuddyTech.API.Models.LeadScore", "CurrentScore")
                        .WithOne()
                        .HasForeignKey("BuddyTech.API.Models.Lead", "CurrentScoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BuddyTech.API.Models.Seller", "Seller")
                        .WithMany("Leads")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CurrentScore");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BuddyTech.API.Models.LeadInteraction", b =>
                {
                    b.HasOne("BuddyTech.API.Models.Lead", "Lead")
                        .WithMany("Interactions")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("BuddyTech.API.Models.LeadScore", b =>
                {
                    b.HasOne("BuddyTech.API.Models.Lead", "Lead")
                        .WithMany("ScoreHistory")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("BuddyTech.API.Models.SellerMission", b =>
                {
                    b.HasOne("BuddyTech.API.Models.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuddyTech.API.Models.Seller", "Seller")
                        .WithMany("Missions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BuddyTech.API.Models.Suggestion", b =>
                {
                    b.HasOne("BuddyTech.API.Models.LeadInteraction", "InteractionSuggested")
                        .WithMany()
                        .HasForeignKey("InteractionSuggestedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuddyTech.API.Models.Lead", "Lead")
                        .WithOne("Suggestion")
                        .HasForeignKey("BuddyTech.API.Models.Suggestion", "LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InteractionSuggested");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("BuddyTech.API.Models.Lead", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("ScoreHistory");

                    b.Navigation("Suggestion");
                });

            modelBuilder.Entity("BuddyTech.API.Models.Seller", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("Missions");
                });
#pragma warning restore 612, 618
        }
    }
}
